title: "MycoAI's website"
author: "MycoAI's community"
description: "Using AI and machine learning to analyze patterns in biodiversity genomics in Fungi."

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "aboutme.md"}
  - {title: "Blogs", file: "index.html"}
  - {title: "Software/Tools", file: "tools.md"}
  - {title: "Publications", file: "publications.md"}
  - {title: "Team members", file: "team.html"}
  - {title: "Projects", icon: github, url: "https://github.com/MycoAI"}
  
external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:d.vu@wi.knaw.nl"}
  - {title: WI, icon: rss, url: "https://wi.knaw.nl/"}
  - {title: Github, icon: github, url: "https://github.com/MycoAI"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
